name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yarn-lint:
    name: yarn lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - run: yarn lint
