name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yarn-commitlint:
    name: yarn commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - name: yarn commitlint
        run: echo "${{ github.event.head_commit.message }}" | yarn commitlint
  yarn-lint:
    name: yarn lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - run: yarn lint
