name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-commit-msg:
    name: Lint commit message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - run: yarn commitlint --from=HEAD~1
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - run: yarn lint
