name: Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
      - run: yarn install
      - name: Run yarn commitlint
        run: echo "${{ github.event.head_commit.message }}" | yarn commitlint
      - name: Run yarn cspell
        run: yarn cspell '**'
      - name: Run yarn prettier --check
        run: yarn prettier --check .
